package bNesis.Sdk.Social.Facebook;
import org.apache.http.HttpStatus;
import java.util.List;
import java.util.Date;
import java.net.URI;


/**
 * An individual entry in a profile's feed. The profile could be a user, page, app, or group. 
 * @typedef {Object} FacebookPost
 */
public class FacebookPost
{
	public FacebookPost(){}
	/**
	 * The post ID
	 * @type {String}
	 */
	public String id;

	/**
	 * The time the post was initially published. For a post about a life event, this will be the date and time of the life event.
	 * @type {Date}
	 */
	public Date created_time;

	/**
	 * The status message in the post.
	 * @type {String}
	 */
	public String message;

	/**
	 * The link attached to this post.
	 * @type {String}
	 */
	public String link;

	/**
	 * Likes.
	 * @type {FacebookUserLikes}
	 */
	public FacebookUserLikes likes;

	/**
	 * Any location information attached to the post.
	 * @type {FacebookPlace}
	 */
	public FacebookPlace place;

	/**
	 * Text from stories not intentionally generated by users, such as those generated when two people become friends, 
	 * or when someone else posts on the person's wall.
	 * @type {String}
	 */
	public String story;

	}

